### ISSUE TITLE
Install without postinstall script?

### ISSUE THREAD

**Issue by zwass** [EverlastingBugstopper/binary-install#6]
## Problem

Running an installed package with `binary-install` on Ubuntu results in the following errors:

After `sudo npm install -g fleetctl`, do the following.

(without `sudo`)
```
$ fleetctl
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir '/usr/local/lib/node_modules/fleetctl/node_modules/binary-install/bin'
    at mkdirSync (fs.js:757:3)
    at new Binary (/usr/local/lib/node_modules/fleetctl/node_modules/binary-install/index.js:48:7)
    at getBinary (/usr/local/lib/node_modules/fleetctl/binary.js:58:10)
    at run (/usr/local/lib/node_modules/fleetctl/binary.js:62:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/fleetctl/run.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

(with `sudo`)
```
$ sudo fleetctl
You must install fleetctl before you can run it
```

## Details

When `npm` is installed with `apt` on Ubuntu, `npm install -g` must be run with `sudo` (due to permissions). [Internet research](https://stackoverflow.com/a/19132229/491710) seems to indicate that postinstall scripts are skipped when `npm` is run as a root user. This leaves the binary un-downloaded after installation when using the example configuration in this repo.

While it seems possible to download the package in the run step, I believe the current `binary-install` API would require the install step to take place on each run.

Do you see a good workaround for this? Is there a good way we could make a `checkInstall` sort of step that would check if the proper version is installed and do so if it's not?

**Comment by zwass** [comment]
FWIW I built a different solution that addressed the issues described. It could easily be refactored to be more modular as is binary-install.

https://github.com/fleetdm/fleet/blob/master/tools/fleetctl-npm/run.js

**Comment by EverlastingBugstopper** [comment]
i've documented the drawbacks of installing tools like this in the [`binary-install` README](https://github.com/EverlastingBugstopper/binary-install/tree/main/packages/binary-install#global-installs-not-recommended)
